/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.xedflix.video.client.user_service_apiclient.api;

import com.xedflix.video.client.user_service_apiclient.model.Organization;
import com.xedflix.video.client.user_service_apiclient.model.OrganizationWithAdmin;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2018-09-07T19:33:07.937+05:30[Asia/Kolkata]")

@Api(value = "OrganizationResource", description = "the OrganizationResource API")
public interface OrganizationResourceApi {

    @ApiOperation(value = "createOrganization", nickname = "createOrganizationUsingPOST", notes = "", response = Organization.class, tags={ "organization-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Organization.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/organizations",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<Organization> createOrganizationUsingPOST(@ApiParam(value = "organization" ,required=true )  @Valid @RequestBody Organization organization);


    @ApiOperation(value = "createOrganizationWithAdmin", nickname = "createOrganizationWithAdminUsingPOST", notes = "", response = OrganizationWithAdmin.class, tags={ "organization-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = OrganizationWithAdmin.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/organizationWithAdmin",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<OrganizationWithAdmin> createOrganizationWithAdminUsingPOST(@ApiParam(value = "organizationWithAdmin" ,required=true )  @Valid @RequestBody OrganizationWithAdmin organizationWithAdmin);


    @ApiOperation(value = "deleteOrganization", nickname = "deleteOrganizationUsingDELETE", notes = "", tags={ "organization-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/organizations/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteOrganizationUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllOrganizations", nickname = "getAllOrganizationsUsingGET", notes = "", response = Organization.class, responseContainer = "List", tags={ "organization-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Organization.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/organizations",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<Organization>> getAllOrganizationsUsingGET(@ApiParam(value = "") @Valid @RequestParam(value = "offset", required = false) Long offset,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "") @Valid @RequestParam(value = "pageNumber", required = false) Integer pageNumber,@ApiParam(value = "") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "") @Valid @RequestParam(value = "paged", required = false) Boolean paged,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort,@ApiParam(value = "") @Valid @RequestParam(value = "sort.sorted", required = false) Boolean sortSorted,@ApiParam(value = "") @Valid @RequestParam(value = "sort.unsorted", required = false) Boolean sortUnsorted,@ApiParam(value = "") @Valid @RequestParam(value = "unpaged", required = false) Boolean unpaged);


    @ApiOperation(value = "getOrganization", nickname = "getOrganizationUsingGET", notes = "", response = Organization.class, tags={ "organization-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Organization.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/organizations/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Organization> getOrganizationUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "updateOrganization", nickname = "updateOrganizationUsingPUT", notes = "", response = Organization.class, tags={ "organization-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Organization.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/organizations",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<Organization> updateOrganizationUsingPUT(@ApiParam(value = "organization" ,required=true )  @Valid @RequestBody Organization organization);

}
