/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.xedflix.video.client.user_service_apiclient.api;

import com.xedflix.video.client.user_service_apiclient.model.OrganizationUser;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2018-09-07T19:33:07.937+05:30[Asia/Kolkata]")

@Api(value = "OrganizationUserResource", description = "the OrganizationUserResource API")
public interface OrganizationUserResourceApi {

    @ApiOperation(value = "createOrganizationUser", nickname = "createOrganizationUserUsingPOST", notes = "", response = OrganizationUser.class, tags={ "organization-user-resource", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "OK", response = OrganizationUser.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/organization-users",
        produces = "*/*",
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<OrganizationUser> createOrganizationUserUsingPOST(@ApiParam(value = "organizationUser" ,required=true )  @Valid @RequestBody OrganizationUser organizationUser);


    @ApiOperation(value = "deleteOrganizationUser", nickname = "deleteOrganizationUserUsingDELETE", notes = "", tags={ "organization-user-resource", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/organization-users/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteOrganizationUserUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllOrganizationUsers", nickname = "getAllOrganizationUsersUsingGET", notes = "", response = OrganizationUser.class, responseContainer = "List", tags={ "organization-user-resource", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "OK", response = OrganizationUser.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/organization-users",
        produces = "*/*",
        method = RequestMethod.GET)
    ResponseEntity<List<OrganizationUser>> getAllOrganizationUsersUsingGET();


    @ApiOperation(value = "getOrganizationUser", nickname = "getOrganizationUserUsingGET", notes = "", response = OrganizationUser.class, tags={ "organization-user-resource", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "OK", response = OrganizationUser.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/organization-users/{id}",
        produces = "*/*",
        method = RequestMethod.GET)
    ResponseEntity<OrganizationUser> getOrganizationUserUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "updateOrganizationUser", nickname = "updateOrganizationUserUsingPUT", notes = "", response = OrganizationUser.class, tags={ "organization-user-resource", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "OK", response = OrganizationUser.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/organization-users",
        produces = "*/*",
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<OrganizationUser> updateOrganizationUserUsingPUT(@ApiParam(value = "organizationUser" ,required=true )  @Valid @RequestBody OrganizationUser organizationUser);

}
